"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import sys
from dotenv import load_dotenv

load_dotenv()


def get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def get_list_env(name, default=''):
    raw_value = os.environ.get(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if 'pytest' in sys.argv[0]:
        # repo-hygiene: allow — fixed test-run key, never used outside pytest.
        SECRET_KEY = 'test-secret-key-with-safe-length-123456'
    else:
        raise RuntimeError('SECRET_KEY must be set in the environment.')

# SECURITY WARNING: don't run with debug turned on in production!
if 'pytest' in sys.argv[0] and 'DEBUG' not in os.environ:
    DEBUG = True
else:
    DEBUG = get_bool_env('DEBUG', False)

ALLOWED_HOSTS = get_list_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = get_list_env(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173'
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt', 
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    # Local
    # `common` holds no models, but must be installed for its management
    # commands (backup_database, restore_database, verify_backup) to be found.
    'common',
    'users',
    'products',
    'inventory',
    'cart',
    'orders',
    'payments',
    'reviews',
    'promotions',
    'storefront',
    'drf_spectacular',
]

MIDDLEWARE = [
    # First, so every log line from this request — including ones emitted by
    # middleware below — carries the correlation id.
    'common.middleware.RequestIDMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------------------------------------------------------------------
# Media (customer-visible uploads: product and category images)
# ---------------------------------------------------------------------------
# Local disk by default. That is adequate for one server and is what production
# runs today, but it has two properties worth knowing:
#
#   1. Uploads live outside the image, so they are NOT part of the immutable
#      artefact and are NOT covered by a database backup. Back up MEDIA_ROOT
#      separately, or move to object storage.
#   2. The VPS deploy runs `git reset --hard`, which deletes files removed from
#      the index. backend/media/ is deliberately still tracked for that reason —
#      see SECURITY_REMEDIATION.md. Moving to object storage is what removes
#      that hazard for good.
#
# To switch to S3-compatible object storage, install django-storages[s3] and set
# MEDIA_STORAGE_BACKEND=storages.backends.s3.S3Storage plus the AWS_* variables.
# No code change is needed; nothing else in the app references the filesystem.
MEDIA_STORAGE_BACKEND = os.environ.get(
    'MEDIA_STORAGE_BACKEND', 'django.core.files.storage.FileSystemStorage'
)

STORAGES = {
    'default': {
        'BACKEND': MEDIA_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# Read by django-storages when object storage is configured. Left empty and
# unused otherwise — no credentials are required to run on local disk.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '') or None
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
# Product images are public; signed URLs would break CDN caching for no benefit.
AWS_QUERYSTRING_AUTH = get_bool_env('AWS_QUERYSTRING_AUTH', False)
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'auth_burst': '5/min',
        # Generous: a provider retrying a legitimate webhook must never be
        # throttled into leaving a payment unsettled.
        'payment_webhook': '600/hour',
    },
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'PakNutrition API',
    'DESCRIPTION': 'E-commerce API for supplements and fitness nutrition store',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8080')
BACKEND_PUBLIC_URL = os.environ.get('BACKEND_PUBLIC_URL', 'http://127.0.0.1:8000')
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin/')

# Payments
SAFEPAY_ENABLED = get_bool_env('SAFEPAY_ENABLED', False)
SAFEPAY_ENV = os.environ.get('SAFEPAY_ENV', 'sandbox')
SAFEPAY_API_KEY = os.environ.get('SAFEPAY_API_KEY', '')
SAFEPAY_SHARED_SECRET = os.environ.get('SAFEPAY_SHARED_SECRET', '')
SAFEPAY_SOURCE = os.environ.get('SAFEPAY_SOURCE', 'paknutrition')
# Webhook verification. Falls back to the shared secret so an existing
# deployment keeps working, but a dedicated webhook secret is preferred.
# The header name and algorithm MUST be confirmed against the Safepay dashboard
# before taking live payments — see backend/payments/providers/safepay.py.
SAFEPAY_WEBHOOK_SECRET = os.environ.get('SAFEPAY_WEBHOOK_SECRET', '')
SAFEPAY_WEBHOOK_SIGNATURE_HEADER = os.environ.get(
    'SAFEPAY_WEBHOOK_SIGNATURE_HEADER', 'HTTP_X_SFPY_SIGNATURE'
)
SAFEPAY_WEBHOOK_SIGNATURE_ALGORITHM = os.environ.get(
    'SAFEPAY_WEBHOOK_SIGNATURE_ALGORITHM', 'sha512'
)
EASYPAISA_ACCOUNT = os.environ.get('EASYPAISA_ACCOUNT', '')
JAZZCASH_ACCOUNT = os.environ.get('JAZZCASH_ACCOUNT', '')
BANK_ACCOUNT_TITLE = os.environ.get('BANK_ACCOUNT_TITLE', '')
BANK_ACCOUNT_NUMBER = os.environ.get('BANK_ACCOUNT_NUMBER', '')
BANK_NAME = os.environ.get('BANK_NAME', '')
MANUAL_PAYMENT_NOTE = os.environ.get(
    'MANUAL_PAYMENT_NOTE',
    'Complete the transfer first, then enter the transaction reference so PakNutrition can verify your payment quickly.',
)

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
ORDER_NOTIFICATION_EMAIL_ENABLED = get_bool_env('ORDER_NOTIFICATION_EMAIL_ENABLED', True)
ORDER_NOTIFICATION_SMS_ENABLED = get_bool_env('ORDER_NOTIFICATION_SMS_ENABLED', False)
ADMIN_PUSH_NOTIFICATIONS_ENABLED = get_bool_env('ADMIN_PUSH_NOTIFICATIONS_ENABLED', True)
EXPO_PUSH_ACCESS_TOKEN = os.getenv('EXPO_PUSH_ACCESS_TOKEN', '')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')

# ---------------------------------------------------------------------------
# Cache and background processing
# ---------------------------------------------------------------------------
# Redis backs both the shared cache and the Celery broker. Without REDIS_URL the
# app still runs: caching becomes a no-op and Celery falls back to running tasks
# inline (see common.dispatch.enqueue). That keeps local development and CI
# working with no extra services, and the production config check refuses to
# start without it.
REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'paknutrition',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', '')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Acknowledge after the task finishes, so a worker killed mid-task returns the
# job to the queue rather than dropping a customer's confirmation email.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
# One at a time: these tasks are network-bound and short, and prefetching just
# parks work on a busy worker while another sits idle.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 120
CELERY_TASK_SOFT_TIME_LIMIT = 90
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Without a broker, run tasks inline so nothing silently stops happening.
CELERY_TASK_ALWAYS_EAGER = get_bool_env('CELERY_TASK_ALWAYS_EAGER', not bool(CELERY_BROKER_URL))
CELERY_TASK_EAGER_PROPAGATES = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# JSON in production so logs are queryable; human-readable locally.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOG_FORMAT = os.environ.get('LOG_FORMAT', 'text' if DEBUG else 'json').lower()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'common.logging.RequestIdFilter',
        },
    },
    'formatters': {
        'json': {
            '()': 'common.logging.JsonFormatter',
        },
        'text': {
            'format': '%(asctime)s %(levelname)-7s [%(request_id)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': LOG_FORMAT if LOG_FORMAT in {'json', 'text'} else 'json',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Payment and webhook activity is the audit trail for money. Always INFO,
        # never suppressed by a raised root level.
        'payments': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'orders': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'paknutrition.request': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'paknutrition.celery': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        # Query logging is deafening and can echo customer data into the log.
        'django.db.backends': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

# ---------------------------------------------------------------------------
# Error monitoring
# ---------------------------------------------------------------------------
# Optional and unconfigured by default. Set SENTRY_DSN to turn it on; no vendor
# is required for the app to run, and nothing is sent anywhere without a DSN.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
SENTRY_ENVIRONMENT = os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development')
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0'))

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.celery import CeleryIntegration
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=SENTRY_ENVIRONMENT,
            integrations=[DjangoIntegration(), CeleryIntegration()],
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            # Customer records must not leave the estate in a crash report.
            send_default_pii=False,
        )
    except ImportError:
        import warnings

        warnings.warn(
            'SENTRY_DSN is set but sentry-sdk is not installed. '
            'Add sentry-sdk to requirements.txt or unset SENTRY_DSN.',
            RuntimeWarning,
        )

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = get_bool_env('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = get_list_env(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173'
)


from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = get_bool_env('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = get_bool_env('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = get_bool_env('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = get_bool_env('SECURE_HSTS_PRELOAD', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True


# ---------------------------------------------------------------------------
# Production configuration validation
# ---------------------------------------------------------------------------
# A misconfigured production box used to boot happily and fail later: a missing
# POSTGRES_DB silently fell back to a SQLite file that deploys overwrite, and
# SAFEPAY_ENABLED without a webhook secret produced a checkout that could never
# settle. Validate at import, report every problem at once, and refuse to start.
#
# Set CONFIG_CHECK_STRICT=0 to downgrade to a warning — for a recovery shell on
# a box that is already broken, not for normal operation.

if not DEBUG and 'pytest' not in sys.argv[0]:
    from common.env import ImproperlyConfigured, validate_production_settings

    _config_problems = validate_production_settings(sys.modules[__name__])
    if _config_problems:
        _report = '\n'.join(f'  - {problem}' for problem in _config_problems)
        _message = (
            f'Refusing to start: {len(_config_problems)} configuration problem(s).\n'
            f'{_report}\n'
            'Fix these in backend/.env, or set CONFIG_CHECK_STRICT=0 to start anyway.'
        )
        if get_bool_env('CONFIG_CHECK_STRICT', True):
            raise ImproperlyConfigured(_message)
        import warnings
        warnings.warn(_message, RuntimeWarning)
