# Generated by Django 4.2.29 on 2026-03-15 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
        ('orders', '0003_order_promotion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_tracker',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('EASYPAISA', 'Easypaisa Transfer'), ('JAZZCASH', 'JazzCash Transfer'), ('BANK_TRANSFER', 'Bank Transfer'), ('SAFEPAY', 'Cards, Wallets & Bank Transfer')], default='COD', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone_number', models.CharField(blank=True, max_length=20)),
                ('applied_promo_code', models.CharField(blank=True, max_length=50)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_address', models.TextField()),
                ('items_snapshot', models.JSONField(blank=True, default=list)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('EASYPAISA', 'Easypaisa Transfer'), ('JAZZCASH', 'JazzCash Transfer'), ('BANK_TRANSFER', 'Bank Transfer'), ('SAFEPAY', 'Cards, Wallets & Bank Transfer')], default='SAFEPAY', max_length=20)),
                ('provider', models.CharField(choices=[('SAFEPAY', 'Safepay')], default='SAFEPAY', max_length=20)),
                ('gateway_tracker', models.CharField(blank=True, max_length=120)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('checkout_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='orders.order')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='promotions.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
