# Generated by Django 5.2.17 on 2026-09-17 16:02

from django.conf import settings
from django.db import migrations, models


def clear_duplicate_trackers(apps, schema_editor):
    """Make existing data satisfy the new unique-tracker constraint.

    The old flow never enforced one-tracker-per-session, so historical rows may
    share a tracker. Settled sessions are left exactly as they are — their
    financial record must not be edited. Only abandoned sessions get their
    tracker cleared, which is harmless: an unsettled session's tracker has no
    further use, and the migration refuses to run if two *settled* sessions
    collide, because that would mean a real double-settlement to investigate
    rather than something a migration should quietly paper over.
    """
    PaymentSession = apps.get_model("orders", "PaymentSession")

    seen = {}
    duplicates = []
    rows = PaymentSession.objects.exclude(gateway_tracker="").order_by("created_at").values(
        "id", "provider", "gateway_tracker", "status"
    )
    for row in rows:
        key = (row["provider"], row["gateway_tracker"])
        if key not in seen:
            seen[key] = row
            continue
        first, second = seen[key], row
        if first["status"] == "COMPLETED" and second["status"] == "COMPLETED":
            raise RuntimeError(
                "Two settled payment sessions share provider tracker "
                f"{row['gateway_tracker']!r} (ids {first['id']} and {second['id']}). "
                "This is a double-settlement and must be investigated before "
                "migrating. Do not bypass this check."
            )
        loser = second if second["status"] != "COMPLETED" else first
        if loser["status"] != "COMPLETED":
            duplicates.append(loser["id"])
        if second["status"] == "COMPLETED":
            seen[key] = second

    if duplicates:
        PaymentSession.objects.filter(id__in=duplicates).update(gateway_tracker="")


def noop(apps, schema_editor):
    """Reverse is a no-op: cleared trackers on abandoned sessions are not restorable."""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_fee_paymentsession_shipping_fee'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='review_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('REVIEW', 'Review Required')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['status', 'created_at'], name='orders_paym_status_edea4d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['gateway_tracker'], name='orders_paym_gateway_54501f_idx'),
        ),
        migrations.RunPython(clear_duplicate_trackers, noop),
        migrations.AddConstraint(
            model_name='paymentsession',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_tracker', ''), _negated=True), fields=('provider', 'gateway_tracker'), name='orders_unique_session_gateway_tracker'),
        ),
    ]
