# Generated by Django 5.2.17 on 2026-09-19 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_backfill_order_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved — awaiting goods'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Goods received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=12)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Arrived damaged'), ('WRONG_ITEM', 'Wrong item sent'), ('NOT_AS_DESCRIBED', 'Not as described'), ('EXPIRED', 'Expired or near expiry'), ('CHANGED_MIND', 'Changed mind'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('staff_note', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('restock', models.BooleanField(blank=True, null=True)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('condition_note', models.CharField(blank=True, default='', max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('FULFILMENT', 'Fulfilment'), ('NOTE', 'Note'), ('REFUND', 'Refund'), ('RETURN', 'Return')], default='FULFILMENT', max_length=16)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(blank=True, default='', max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_customer_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the system did it, e.g. a verified payment webhook.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Order history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_2e8185_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-requested_at'], name='orders_retu_status_d2b8a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_return_item_quantity_positive'),
        ),
    ]
