[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py *_tests.py
testpaths =
    users
    products
    cart
    orders
    reviews
    promotions
norecursedirs =
    venv
    .venv
    __pycache__
