# Generated by Django 5.2.17 on 2026-09-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_backfill_catalog_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=12),
        ),
    ]
