# Generated by Django 5.2.17 on 2026-09-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=160)),
                ('action', models.CharField(choices=[('inventory.receive', 'Received stock'), ('inventory.adjust', 'Adjusted stock'), ('inventory.stocktake', 'Recorded a physical count'), ('order.transition', 'Moved an order'), ('order.cancel', 'Cancelled an order'), ('order.refund', 'Refunded an order'), ('return.approve', 'Approved a return'), ('return.reject', 'Rejected a return'), ('return.receive', 'Received returned goods'), ('payment.review', 'Resolved a payment held for review'), ('catalog.create', 'Created a catalogue record'), ('catalog.update', 'Updated a catalogue record'), ('catalog.publish', 'Published a product'), ('catalog.unpublish', 'Unpublished a product'), ('catalog.delete', 'Deleted a catalogue record'), ('promotion.create', 'Created a promotion'), ('promotion.update', 'Changed a promotion'), ('customer.update', 'Edited a customer'), ('staff.update', 'Changed staff access')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entity_label', models.CharField(blank=True, default='', help_text='Readable name at the time.', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the system acted, or when the account was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='operations__entity__5626e6_idx'), models.Index(fields=['actor', '-created_at'], name='operations__actor_i_20ba8a_idx'), models.Index(fields=['action', '-created_at'], name='operations__action_e02f6e_idx')],
            },
        ),
    ]
