# Generated by Django 5.2.17 on 2026-09-17 16:02

from django.db import migrations, models


def clamp_over_redeemed(apps, schema_editor):
    """Existing rows may already exceed their limit under the old racy increment.

    Raise used_count's ceiling rather than lower the count: the redemptions
    happened, so discarding them would misstate how often a coupon was used.
    Lifting usage_limit to match records reality and lets the constraint apply
    from here on.
    """
    Promotion = apps.get_model("promotions", "Promotion")
    over = Promotion.objects.filter(used_count__gt=models.F("usage_limit"))
    for promotion in over:
        promotion.usage_limit = promotion.used_count
        promotion.save(update_fields=["usage_limit"])


def noop(apps, schema_editor):
    """Reverse is a no-op — the original limits are not recoverable."""


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clamp_over_redeemed, noop),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('used_count__lte', models.F('usage_limit'))), name='promotions_used_count_within_limit'),
        ),
    ]
