# Generated by Django 5.2.17 on 2026-09-17 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_paymentsession_expires_at_and_more'),
        ('products', '0004_goal_productmedia_productvariant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('is_fulfilment', models.BooleanField(default=True)),
                ('is_pickup_point', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='inventory_single_default_location')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='products.productvariant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventorylocation')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'variant'], name='inventory_i_locatio_cfb254_idx'), models.Index(fields=['variant'], name='inventory_i_variant_df5e3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('variant', 'location'), name='inventory_one_balance_per_variant_location'), models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='inventory_on_hand_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='inventory_reserved_not_negative'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='inventory_reserved_within_on_hand')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock received'), ('SALE', 'Sold'), ('RETURN', 'Returned by customer'), ('CANCELLATION', 'Order cancelled'), ('DAMAGE', 'Damaged or written off'), ('MANUAL_ADJUSTMENT', 'Manual adjustment'), ('STOCKTAKE', 'Physical count correction')], db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('balance_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the system posted it, e.g. a sale at checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorylocation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='inventory_s_variant_608d8a_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_movement_quantity_not_zero')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventorylocation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'), models.Index(fields=['reference', 'status'], name='inventory_s_referen_803dfe_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('reference', 'variant'), name='inventory_one_active_reservation_per_reference_variant'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_reservation_quantity_positive')],
            },
        ),
    ]
