# Generated by Django 5.2.17 on 2026-09-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_paymentsession_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SAFEPAY', 'Safepay')], default='SAFEPAY', max_length=20)),
                ('provider_reference', models.CharField(max_length=190)),
                ('provider_tracker', models.CharField(blank=True, db_index=True, default='', max_length=190)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_currency', models.CharField(default='PKR', max_length=3)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('verified_currency', models.CharField(blank=True, default='', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('MISMATCH', 'Mismatch — held for review')], default='INITIATED', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='orders.order')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.paymentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('event_id', models.CharField(max_length=190)),
                ('body_digest', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('REPLAY', 'Replay — ignored'), ('REJECTED', 'Rejected'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_c3bda6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['settled_at'], name='payments_pa_settled_840126_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_reference'), name='payments_unique_provider_reference'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'received_at'], name='payments_we_provide_f04141_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['result'], name='payments_we_result_eb384d_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='payments_unique_webhook_event'),
        ),
    ]
