# Generated by Django 4.2.29 on 2026-03-24 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(blank=True, default='', max_length=120)),
                ('expo_push_token', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_admin_user_id_b390f4_idx'), models.Index(fields=['installation_id'], name='users_admin_install_9937ba_idx')],
            },
        ),
    ]
